name: concur
description: Help your Web Workers get on the same page with Concur!
version: 0.1.1
repository: https://github.com/cthonianmessiah/concur

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.3

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
