name: concur
description: A helper for making multithreaded web applications using Web Workers.  Seamlessly downgrades to async on one thread when asked or when Web Workers are not supported.
version: 0.1.2
repository: https://github.com/cthonianmessiah/concur

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.3

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
