name: concur
description: Help your Web Workers get on the same page with Concur!
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.3
  build_runner: '>=1.6.2 <3.0.0'

dev_dependencies:
  build_web_compilers: '>=2.12.0 <4.0.0'
  pedantic: ^1.10.0
  test: ^1.16.0
